test_dict = {'data': [
	{'id'                : 'mkgLWxrxpB', 'name': 'P9000 Series Compute Pool 5', 'currency_code': None,
	 'cpu_hourly_price'  : None, 'ram_hourly_price': None, 'hdd_hourly_price': None, 'management_type': 'api',
	 'management_url'    : 'https://10.0.1.120', 'master_ip_addr': '10.0.1.120', 'port': 443,
	 'pool_type'         : 'clustered', 'virtualization': 'XenServer', 'virtualization_version': '6.2',
	 'is_active'         : True, 'datacenter_id': 'mkgLWxrxpB', 'datacenter_name': 'Telecom Italia Sparkle',
	 'datacenter_node_id': 'mkgLWxrxpB', 'datacenter_node_name': 'Enterprise Node 5', 'product_id': None,
	 'product_name'      : None, 'vendor_id': 'LGBElZNMyY', 'vendor_name': 'Şef Bilişim Hizmetleri A.ş.'},
	{'id'                : 'yVMNlGrzlo', 'name': 'Management Node 2 Compute Pool', 'currency_code': None,
	 'cpu_hourly_price'  : None, 'ram_hourly_price': None, 'hdd_hourly_price': None, 'management_type': 'api',
	 'management_url'    : 'https://10.100.0.216', 'master_ip_addr': '10.100.0.216', 'port': 443, 'pool_type': 'farm',
	 'virtualization'    : 'XenServer', 'virtualization_version': '8.0', 'is_active': True,
	 'datacenter_id'     : 'mkgLWxrxpB', 'datacenter_name': 'Telecom Italia Sparkle',
	 'datacenter_node_id': 'yVMNlGrzlo', 'datacenter_node_name': 'Management Node 2.0', 'product_id': None,
	 'product_name'      : None, 'vendor_id': 'LGBElZNMyY', 'vendor_name': 'Şef Bilişim Hizmetleri A.ş.'},
	{'id'                : 'GqdrRBrPeE', 'name': 'Radore Compute Member Pool', 'currency_code': None,
	 'cpu_hourly_price'  : None, 'ram_hourly_price': None, 'hdd_hourly_price': None, 'management_type': 'api',
	 'management_url'    : 'https://31.210.66.66', 'master_ip_addr': '31.210.66.66', 'port': 443,
	 'pool_type'         : 'clustered', 'virtualization': 'XenServer', 'virtualization_version': '8.0',
	 'is_active'         : False, 'datacenter_id': 'zVGNXorAoR', 'datacenter_name': 'Radore',
	 'datacenter_node_id': 'GqdrRBrPeE', 'datacenter_node_name': 'Radore Testing Node', 'product_id': None,
	 'product_name'      : None, 'vendor_id': 'LGBElZNMyY', 'vendor_name': 'Şef Bilişim Hizmetleri A.ş.'},
	{'id'              : 'vyGLGyNoWk', 'name': 'Radius Compute Pool', 'currency_code': None, 'cpu_hourly_price': None,
	 'ram_hourly_price': None, 'hdd_hourly_price': None, 'management_type': 'api',
	 'management_url'  : 'https://90.159.16.88', 'master_ip_addr': '90.159.16.88', 'port': 443, 'pool_type': 'farm',
	 'virtualization'  : 'XenServer', 'virtualization_version': '7.5', 'is_active': True, 'datacenter_id': 'vyGLGyNoWk',
	 'datacenter_name' : 'Radius Demo Center', 'datacenter_node_id': None, 'datacenter_node_name': None,
	 'product_id'      : None, 'product_name': None, 'vendor_id': 'LGBElZNMyY',
	 'vendor_name'     : 'Şef Bilişim Hizmetleri A.ş.'},
	{'id'                : 'zVGNXorAoR', 'name': 'İşnet Cloud Compute Pool', 'currency_code': None,
	 'cpu_hourly_price'  : None, 'ram_hourly_price': None, 'hdd_hourly_price': None, 'management_type': 'api',
	 'management_url'    : 'https://172.16.197.10', 'master_ip_addr': '192.16.197.10', 'port': 443,
	 'pool_type'         : 'clustered', 'virtualization': 'XenServer', 'virtualization_version': '8.2',
	 'is_active'         : True, 'datacenter_id': 'bGyYjGLExD', 'datacenter_name': 'İşnet İşkule Datacenter',
	 'datacenter_node_id': 'bGyYjGLExD', 'datacenter_node_name': 'İşnet Cloud', 'product_id': None,
	 'product_name'      : None, 'vendor_id': 'LGBElZNMyY', 'vendor_name': 'Şef Bilişim Hizmetleri A.ş.'},
	{'id'                : 'EzpLperabX', 'name': 'Veeam Controller Pool', 'currency_code': None,
	 'cpu_hourly_price'  : None, 'ram_hourly_price': None, 'hdd_hourly_price': None, 'management_type': 'api',
	 'management_url'    : 'https://10.0.2.10', 'master_ip_addr': '10.0.2.10', 'port': 443, 'pool_type': 'farm',
	 'virtualization'    : 'XenServer', 'virtualization_version': '8.0', 'is_active': True,
	 'datacenter_id'     : 'mkgLWxrxpB', 'datacenter_name': 'Telecom Italia Sparkle',
	 'datacenter_node_id': 'RZMLnqYGja', 'datacenter_node_name': 'Veeam Cloud Controller Node',
	 'product_id'        : 'bkVNkykLlw', 'product_name': 'Veeam Cloud Server', 'vendor_id': 'LGBElZNMyY',
	 'vendor_name'       : 'Şef Bilişim Hizmetleri A.ş.'},
	{'id'              : 'jnmYEDPNQa', 'name': 'SY. backup', 'currency_code': None, 'cpu_hourly_price': None,
	 'ram_hourly_price': None, 'hdd_hourly_price': None, 'management_type': 'api',
	 'management_url'  : 'https://10.0.1.120', 'master_ip_addr': '10.0.1.120', 'port': 443, 'pool_type': 'clustered',
	 'virtualization'  : 'UrBackup', 'virtualization_version': '6.2', 'is_active': True, 'datacenter_id': 'mkgLWxrxpB',
	 'datacenter_name' : 'Telecom Italia Sparkle', 'datacenter_node_id': None, 'datacenter_node_name': None,
	 'product_id'      : None, 'product_name': None, 'vendor_id': 'LGBElZNMyY',
	 'vendor_name'     : 'Şef Bilişim Hizmetleri A.ş.'}]}
